Feature/add hilt dependency
ShyPolarBear/Android pull request #10
Opened 2023-05-21 13:15 UTC by BeamjunCho9

## 📌 PR 요약

🌱 작업한 내용
- Hilt Dependency 추가
- DI 패키지 추가
- Application class 추가
- build gradle .kts 파일로 변환
- compose 제거

🌱 PR 포인트
- commit을 chore와 feature 2개로 나눠서 하였습니다. 

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #9

2023-05-21 13:24 UTC, jinukeu requested changes

2023-05-21 13:24 UTC, jinukeu commented on app/src/main/java/com/shypolarbear/android/ui/theme/Color.kt
> +//val Pink40 = Color(0xFF7D5260)
컴포즈 관련 파일이라 주석처리 하지 않고 아예 삭제해도 될 것 같습니다.

2023-05-21 13:24 UTC, jinukeu commented on app/src/main/java/com/shypolarbear/android/ui/theme/Theme.kt
> +//}
컴포즈 관련 파일이라 주석처리 하지 않고 아예 삭제해도 될 것 같습니다.

2023-05-21 13:24 UTC, jinukeu commented on app/src/main/java/com/shypolarbear/android/ui/theme/Type.kt
> +//)
컴포즈 관련 파일이라 주석처리 하지 않고 아예 삭제해도 될 것 같습니다.

2023-05-21 13:24 UTC, jinukeu commented on build.gradle.kts
> +//}
git에 기록이 따로 남으니 굳이 주석처리 하지 않고 지워버리는게 더 깔끔할 것 같아요

2023-05-22 06:00 UTC, BEEEAM-J commented
리뷰 사항 다 수정하였습니다~!

2023-05-22 06:27 UTC, jinukeu approved these changes

2023-05-22 06:28 UTC, merged