Feature/add retrofit
ShyPolarBear/Android pull request #12
Opened 2023-05-24 08:51 UTC by BeamjunCho9

## 📌 PR 요약

🌱 작업한 내용
- retrofit, okHttp, coroutine 의존성 추가
- NetworkModule 생성
- ApiModule 생성
- 예제api 생성

🌱 PR 포인트
- app 모듈 -> retrofit (의존성 주입을 해줘야 하기 때문에 retrofit 추가)
data 모듈 -> retrofit, coroutine (data 모듈에서 통신하여 데이터를 받아오기 때문에 retrofit과 coroutine을 추가)
domain 모듈 -> x
presentation 모듈 -> coroutine (통신을 하지 않기 때문에 coroutine만 추가)

- NetworkModule로 retrofit 객체를 생성하고 ApiModule에서 각 Api에 맞게 create 하여 사용하려고 합니다.
- 예제 api와 model을 만들어서 사용하려는 형식을 정의 하였습니다. (이후 수정해서 사용 할 예정)

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #11

2023-05-24 08:59 UTC, jinukeu requested changes

2023-05-24 08:59 UTC, jinukeu commented on buildSrc/src/main/java/Versions.kt
> +    const val KOTLINX_COROUTINE = "1.3.9"
코루틴 최신 버전이 1.3.9인가요?

2023-05-25 04:14 UTC, BeamjunCho9 commented on buildSrc/src/main/java/Versions.kt
> +    const val KOTLINX_COROUTINE = "1.3.9"
1.7.1로 변경 하였습니다.

2023-05-25 04:21 UTC, jinukeu commented
수정 사항 반영 후 코멘트 한번만 남겨주세요! @BeamjunCho9

2023-05-25 04:23 UTC, BeamjunCho9 commented
넵!

2023-05-25 04:25 UTC, jinukeu commented
테스트 한번만 할게용

2023-05-25 04:25 UTC, jinukeu approved these changes

2023-05-25 05:15 UTC, merged