Feature/create base classes
ShyPolarBear/Android pull request #16
Opened 2023-05-31 09:55 UTC by BeamjunCho9

## 📌 PR 요약

🌱 작업한 내용
- Base Activity 추가
- Base Fragment 추가
- Base ViewModel 추가
- Sample Data 받아오기 추가

🌱 PR 포인트
- Base Acticity, Base Fragment, Base ViewModel 추가 하였습니다.
- Sample Data를 받아서 Data Binding을 사용하여 화면에 출력 하는 예제를 추가하였습니다.
- 흐름: Fragment -> UseCase -> RepositoryImp -> Api 요청
![데이터 요청 흐름](https://github.com/ShyPolarBear/Android/assets/107917980/73eb30f1-83bd-41b9-a5e8-d60122019333)

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #13

2023-05-31 09:59 UTC, jinukeu requested changes
오호 ... 데이터 흐름까지 ... 아주 굳굳입니다

2023-05-31 09:59 UTC, jinukeu commented on app/src/main/java/com/shypolarbear/android/di/NetworkModule.kt
> +    const val SAMPLEURL = "https://api.chucknorris.io/"
SAMPLEURL -> SAMPLE_URL 이 가독성이 더 좋을 것 같습니다

2023-05-31 10:01 UTC, jinukeu requested changes
Main말구 Sample 관련 패키지 만들어서 작업부탁드릴게요!

2023-06-03 09:13 UTC, BeamjunCho9 commented
피드백 반영하여 수정하였습니다!

2023-06-03 09:52 UTC, jinukeu requested changes

2023-06-03 09:52 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/sample/SampleActivity.kt
> +    Timber.plant(Timber.DebugTree())
https://github.com/JakeWharton/timber#usage

Usage
Two easy steps:

**Install any Tree instances you want in the onCreate of your application class.**
Call Timber's static methods everywhere throughout your app.

Application에서 Timber 세팅해주세요

2023-06-04 12:27 UTC, BeamjunCho9 commented
수정하였습니다.

2023-06-04 13:04 UTC, jinukeu approved these changes

2023-06-04 13:08 UTC, merged