[WBS-104]Feature/create splash
ShyPolarBear/Android pull request #19
Opened 2023-06-08 12:11 UTC by BeamjunCho9

## 📌 PR 요약

🌱 작업한 내용
- Splash 화면 추가

🌱 PR 포인트
- Figma에서 splash 아이콘을 svg형식으로 다운 받아서 안드로이드에 vector asset으로 추가할 때 오류가 생겨서 png 파일로 적용하였습니다. 

## 📸 스크린샷
|스크린샷|
|:--:|
|![KakaoTalk_20230608_210143803](https://github.com/ShyPolarBear/Android/assets/107917980/4b0682eb-9658-4001-9c60-7d10e0ca92c3)|

## 📮 관련 이슈
- Resolved: #17

2023-06-08 12:26 UTC, jinukeu requested changes

2023-06-08 12:26 UTC, jinukeu commented on buildSrc/src/main/java/Versions.kt
> +    const val SPLASHSCREEN = "1.0.0-alpha02"
SPLASH_SCREEN 으로 네이밍 변경 부탁드릴게요!

https://developer.android.com/jetpack/androidx/releases/core?hl=ko
알파 버전 말고 안정화 버전인 1.0.0 쓰는거 어떤가요?

2023-06-08 12:26 UTC, jinukeu commented on presentation/build.gradle.kts
> +    // Splash Screen api
주석 없어도 될 것 같아요 (AndroidX.SPLASHSCREEN를 보고 어떤 라이브러리인지 충분이 추론 가능하므로)

2023-06-08 12:26 UTC, jinukeu commented on presentation/src/main/res/drawable/ic_splash_mark.PNG
이거 피그마에서 추출하실 때 x4 옵션으로 하신거 맞나요?

2023-06-08 12:27 UTC, jinukeu commented
스크린샷의 경우 동영상으로 첨부해주시면 더 좋을 것 같습니다. (스플래시 화면처럼 애니메이션이 들어간 경우)

사진 첨부하듯이 동영상 첨부할 수 있어요

2023-06-08 12:45 UTC, BeamjunCho9 commented on presentation/src/main/res/drawable/ic_splash_mark.PNG
x1 옵션으로 추출하였습니다. 그리고 원본 그대로 적용하면 이미지가 짤리면서 원형 모양이 안나와서 흰색 배경에서 여백을 두고 캡처 하여 적용하였습니다.

2023-06-08 13:45 UTC, jinukeu commented on presentation/src/main/res/drawable/ic_splash_mark.PNG
캡처를 하는 경우 이미지 품질 하락 이슈가 있어서 피그마 디자인가이드에 로고를 여러개 추가해놨습니다. 여기서 골라서 쓰시면 될 것 같아요!

다음에도 디자인 관련 이슈가 있다면 말씀해주세요!

2023-06-09 01:38 UTC, jinukeu approved these changes

2023-06-09 01:42 UTC, merged