[WBS-108]Feature: UiState 사용하는 Sample 추가
ShyPolarBear/Android pull request #20
Opened 2023-06-16 04:30 UTC by BeamjunCho9

## 📌 PR 요약

🌱 작업한 내용
- Ui State를 Sample에 적용하였습니다. 

🌱 PR 포인트
- ViewModel에서 sample 데이터를 받아오는지 여부를 확인하여 Ui State로 동작을 선언하였습니다.
- Ui State에 따라 동작하는 것을 확인하기 위해 Progress Bar를 넣어 카테고리가 로딩 되는 동안에만 나타나게 하였습니다.
- runCatching과 Result를 사용하여 에러 핸들링을 하게 하였습니다.
- api를 repositoryimp에서 호출하고, runCatching을 통해서 해당 함수의 실행 결과를 Result 객체에 담아서 UseCase로 반환합니다. ViewModel 에서는 Result 객체를 onSuccess, onFailure를 통해서 동작이 성공했는지 실패했는지 판단하고, Ui의 상태를 정의 하게 하였습니다.

참고
- https://dev-repository.tistory.com/105

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #18

2023-06-16 05:56 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/sample/SampleViewModel.kt
> +                null -> {
loadedSample 값이 null이 될 수 있나요?

2023-06-17 11:12 UTC, BeamjunCho9 commented on presentation/src/main/java/com/shypolarbear/presentation/sample/SampleViewModel.kt
> +                null -> {
생각해보니 null이 될 수 없어서 수정하였습니다.

2023-06-17 12:23 UTC, jinukeu requested changes
1. app 모듈의 AndroidManifest.xml에서 activity 관련 코드는 presentation 모듈의 AndroidManifest.xml로 옮겨주세요.

2.
```kotlin
interface ExampleApi {
    @GET("jokes/categories")
    suspend fun getExample(): Response<ExampleModel>
}
```
Response 객체로 감싸주세요.

Response로 감싸는 경우 다음과 같은 이점이 있습니다.
1. Http Status Code를 알아낼 수 있습니다.
2. Response로 감싸지 않는 경우 Http Status Code가 200 ~ 300 사이에 있지 않은 경우, 사용자의 네트워크가 불안정한 경우 모두 onFailure로 값이 내려오게됩니다. 

예를들어 Http Status Code가 400, 404 두 가지 경우로 내려온다고 가정했을 때, Response 객체로 감싸지 않으면 Http Status Code가 400인지 404인지 알아낼 방법이 없습니다.

https://toss.tech/article/kotlin-result
위 블로그에서도 커스텀된 Response(`OtherServiceResponse`)로 객체를 감싸고 있는 것을 확인할 수 있습니다.
```kotlin
// API client
@FeignClient
internal interface LoginApi {
  @PostMapping
  fun login(
    @RequestBody request: LoginRequestDto
  ): OtherServiceResponse<LoginResponseDto>
}
```

이 외의 코드는 너무 좋습니다. (특히 State 부분 ... 깜짝 놀랐네요)

2023-06-17 12:23 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/sample/SampleViewModel.kt
> +    private val _sampleState: MutableStateFlow<SampleState> = MutableStateFlow(SampleState(true, false, ""))
https://memostack.tistory.com/221

named argument 사용하면 더 좋을 것 같아요!
ex)
```kotlin
SampleState(
 loading=true,
 error = false,
 category = ""
)
```

2023-06-17 12:23 UTC, lluke0 commented on data/src/main/java/com/shypolarbear/data/repositoryimp/ExampleRepoImp.kt
>  class ExampleRepoImp @Inject constructor (
Imp -> Impl로 이름 변경해주세용

2023-06-20 18:14 UTC, BeamjunCho9 commented
리뷰 반영해서 수정하였습니다.

2023-06-21 04:25 UTC, jinukeu approved these changes
Http 에러와 그 외의 Exception을 구분지어 처리하도록 코드를 수정했습니다.
조금 더 좋은 코드를 작성할 수 있지만, 일단 이 정도 코드로 작업하는게 학습 효율이 좋을 것 같습니다.

코드 한번 살펴보시고 괜찮은 것 같으면 develop 브랜치에 Merge 부탁드립니다.

2023-06-21 12:33 UTC, merged