[WBS-125]Featrue/create feed post UI
ShyPolarBear/Android pull request #27
Opened 2023-07-03 05:24 UTC by BeamjunCho9

## 📌 PR 요약

🌱 작업한 내용
- 피드 전체 UI 구현

🌱 PR 포인트
- 링크를 통해 이미지를 업로드 하기 위해서 Glide 라이브러리를 추가하였습니다. 
참고
https://github.com/bumptech/glide
https://blog.yena.io/studynote/2020/06/10/Android-Glide.html

- 피드 전체를 Recycler View의 아이템으로 담아서 출력하였습니다. 각 아이템의 클릭 이벤트는 Recycler View의 ViewHolder에 정의하였고 피드 내의 게시물 이미지 업로드는 ViewPager의 ViewHolder에 정의하였습니다.
- 좋아요 X개 와 같이 텍스트 중간에 변경되어야 하는 숫자가 있는 경우  처리의 편의성을 위해서 '좋아요', 'X', '개' 와 같이 TextView를 나눠서 정의하였습니다. 

## 📸 스크린샷
|스크린샷|
|:--:|
|https://github.com/ShyPolarBear/Android/assets/107917980/aebed5a7-eed7-4bee-bfd4-c854967b392a|

## 📮 관련 이슈
- Resolved: #23

2023-07-03 06:19 UTC, kimmandoo commented on presentation/src/main/res/values/themes.xml
> +    <style name="Theme.ShyPolarBear" parent="Theme.MaterialComponents.Light.NoActionBar" />
AppCompat에서 바꾼이유가 카드뷰 때문인가요??

2023-07-03 06:34 UTC, BeamjunCho9 commented on presentation/src/main/res/values/themes.xml
> +    <style name="Theme.ShyPolarBear" parent="Theme.MaterialComponents.Light.NoActionBar" />
네네 맞습니다! 기본 CardView는 xml 상에서 속성을 통해 테두리의 두께나 색상 정의가 안되지만 MaterialCardView에서는 되기 때문에 변경하였습니다.
테마를 Material로 바꾸 점이 추후에 문제가 될 경우 다시 appCompat으로 변경하고 아래의 방법을 이용하여 cardView를 디자인 하면 될 거 같습니다.

https://we-always-fight-with-code.tistory.com/m/86

2023-07-03 07:44 UTC, jinukeu reviewed
피드 이미지, 댓글 영역에 들어간 그림자 제거해주세요

2023-07-03 07:44 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/FeedFragment.kt
> +    private val feedSortItems: List<PowerMenuItem> = listOf(PowerMenuItem("최신"), PowerMenuItem("최근 인기"), PowerMenuItem("best"))
하드 코딩 제거해주세요

2023-07-03 07:48 UTC, jinukeu requested changes

2023-07-03 07:48 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +    private val feedPostPropertyItems: List<PowerMenuItem> = listOf(PowerMenuItem("수정"), PowerMenuItem("삭제"), PowerMenuItem("신고"), PowerMenuItem("차단"))
하드 코딩 제거해주세요

2023-07-03 07:48 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +        private var IS_FEED_REPLY_LIKE = false
IS_FEED_REPLY_LIKE , IS_FEED_LIKE 를 companion object로 한 이유가 있나요?

2023-07-03 07:48 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +            0 -> {
0과 1로는 이 코드가 어떤 코드인지 파악하기 너무 어려울 것 같아요

2023-07-03 07:48 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +        val on = ContextCompat.getDrawable(binding.root.context, R.drawable.ic_btn_like_on)
좀 더 명확한 변수 이름으로 변경 부탁드립니다

2023-07-03 16:57 UTC, BeamjunCho9 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +        private var IS_FEED_REPLY_LIKE = false
제가 companion object를 잘못 이해해서 그랬네요...ㅎㅎ
수정하였습니다.

2023-07-04 07:09 UTC, BeamjunCho9 commented
> 피드 이미지, 댓글 영역에 들어간 그림자 제거해주세요

궁금한게 생겼는데 만약 세로로 사진을 찍은 경우에는 이미지를 어떻게 보여줘야 하나요??
 -> viewPager 내에 이미지를 꽉채워서 보이게 할지 or 이미지 원본을 보여주고 남는 공간은 하얀 배경으로 보이게 할지 (이 경우도 이미지 끝에 radius를 넣어야 하는지)

2023-07-04 07:10 UTC, jinukeu commented
> > 피드 이미지, 댓글 영역에 들어간 그림자 제거해주세요
> 
> 궁금한게 생겼는데 만약 세로로 사진을 찍은 경우에는 이미지를 어떻게 보여줘야 하나요?? -> viewPager 내에 이미지를 꽉채워서 보이게 할지 or 이미지 원본을 보여주고 남는 공간은 하얀 배경으로 보이게 할지 (이 경우도 이미지 끝에 radius를 넣어야 하는지)

첫번째 방법 + centerCrop으로 부탁드립니다!

2023-07-04 07:12 UTC, BeamjunCho9 commented
>

2023-07-04 07:14 UTC, BeamjunCho9 commented
> > > 피드 이미지, 댓글 영역에 들어간 그림자 제거해주세요
> > 
> > 
> > 궁금한게 생겼는데 만약 세로로 사진을 찍은 경우에는 이미지를 어떻게 보여줘야 하나요?? -> viewPager 내에 이미지를 꽉채워서 보이게 할지 or 이미지 원본을 보여주고 남는 공간은 하얀 배경으로 보이게 할지 (이 경우도 이미지 끝에 radius를 넣어야 하는지)
> 
> 첫번째 방법 + centerCrop으로 부탁드립니다!

해당 방법으로 설정하면 세로로 더 긴 이미지가 짤려서 나오는데 괜찮을까요??
ex)
![EpAAHXnUcAALN6t](https://github.com/ShyPolarBear/Android/assets/107917980/d8fc0775-8e58-4114-aa1a-9bbf229fcee3)
![KakaoTalk_20230704_161317655](https://github.com/ShyPolarBear/Android/assets/107917980/cca36d30-5bc8-4da9-b738-d8b039cb0a28)

2023-07-04 07:16 UTC, jinukeu commented
> > > > 피드 이미지, 댓글 영역에 들어간 그림자 제거해주세요
> > > 
> > > 
> > > 궁금한게 생겼는데 만약 세로로 사진을 찍은 경우에는 이미지를 어떻게 보여줘야 하나요?? -> viewPager 내에 이미지를 꽉채워서 보이게 할지 or 이미지 원본을 보여주고 남는 공간은 하얀 배경으로 보이게 할지 (이 경우도 이미지 끝에 radius를 넣어야 하는지)
> > 
> > 
> > 첫번째 방법 + centerCrop으로 부탁드립니다!
> 
> 해당 방법으로 설정하면 세로로 더 긴 이미지가 짤려서 나오는데 괜찮을까요?? ex) ![EpAAHXnUcAALN6t](https://user-images.githubusercontent.com/107917980/250795482-d8fc0775-8e58-4114-aa1a-9bbf229fcee3.jpg) ![KakaoTalk_20230704_161317655](https://user-images.githubusercontent.com/107917980/250795497-cca36d30-5bc8-4da9-b738-d8b039cb0a28.jpg)

넵 (보통은 이렇게 타협하더라구요 ㅜㅜ) 
아니면 적절한 라이브러리를 사용하여 이미지 크롭 기능을 추가하셔도 좋습니다!

2023-07-04 07:18 UTC, BeamjunCho9 commented
> > > > 피드 이미지, 댓글 영역에 들어간 그림자 제거해주세요
> > > 
> > > 
> > > 궁금한게 생겼는데 만약 세로로 사진을 찍은 경우에는 이미지를 어떻게 보여줘야 하나요?? -> viewPager 내에 이미지를 꽉채워서 보이게 할지 or 이미지 원본을 보여주고 남는 공간은 하얀 배경으로 보이게 할지 (이 경우도 이미지 끝에 radius를 넣어야 하는지)
> > 
> > 
> > 첫번째 방법 + centerCrop으로 부탁드립니다!
> 
> 해당 방법으로 설정하면 세로로 더 긴 이미지가 짤려서 나오는데 괜찮을까요?? ex) ![EpAAHXnUcAALN6t](https://user-images.githubusercontent.com/107917980/250795482-d8fc0775-8e58-4114-aa1a-9bbf229fcee3.jpg) ![KakaoTalk_20230704_161317655](https://user-images.githubusercontent.com/107917980/250795497-cca36d30-5bc8-4da9-b738-d8b039cb0a28.jpg)




> > > > > 피드 이미지, 댓글 영역에 들어간 그림자 제거해주세요
> > > > 
> > > > 
> > > > 궁금한게 생겼는데 만약 세로로 사진을 찍은 경우에는 이미지를 어떻게 보여줘야 하나요?? -> viewPager 내에 이미지를 꽉채워서 보이게 할지 or 이미지 원본을 보여주고 남는 공간은 하얀 배경으로 보이게 할지 (이 경우도 이미지 끝에 radius를 넣어야 하는지)
> > > 
> > > 
> > > 첫번째 방법 + centerCrop으로 부탁드립니다!
> > 
> > 
> > 해당 방법으로 설정하면 세로로 더 긴 이미지가 짤려서 나오는데 괜찮을까요?? ex) ![EpAAHXnUcAALN6t](https://user-images.githubusercontent.com/107917980/250795482-d8fc0775-8e58-4114-aa1a-9bbf229fcee3.jpg) ![KakaoTalk_20230704_161317655](https://user-images.githubusercontent.com/107917980/250795497-cca36d30-5bc8-4da9-b738-d8b039cb0a28.jpg)
> 
> 넵 (보통은 이렇게 타협하더라구요 ㅜㅜ) 아니면 적절한 라이브러리를 사용하여 이미지 크롭 기능을 추가하셔도 좋습니다!

넵 알겠습니다!

2023-07-04 08:06 UTC, BeamjunCho9 commented
피드백 전부 반영하였습니다.

2023-07-04 08:31 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +    private var IS_FEED_LIKE = false
변경되는 변수이므로 카멜 케이스로 바꾸는게 좋을거같아용

2023-07-04 09:00 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +    private var IS_FEED_LIKE = false
네넵 수정하였습니다!

2023-07-04 09:01 UTC, jinukeu approved these changes

2023-07-04 09:03 UTC, kimmandoo approved these changes

2023-07-04 09:05 UTC, merged