[WBS-143]Feature/create feed detail UI
ShyPolarBear/Android pull request #32
Opened 2023-07-13 06:47 UTC by BEEEAM-J

## 📌 PR 요약

🌱 작업한 내용
- 피드 자세히보기 UI 구현
- 피드의 게시물 클릭 시 자세히보기로, 자세히보기에서 뒤로가기 버튼 클릭 시 피드 전체 조회로 이동 구현
- jetpack navigation 적용

🌱 PR 포인트
- 한 recyclerView 안에 여러 상태의 댓글들을 보여주기 위해서 viewType을 지정하여 구분하였습니다. 
- 댓글과 대댓글은 각각 comment, reply로 구분하였습니다.
- 댓글의 작성자에 따라 속성이 다르게 보이게 하기 위해서 viewHolder에서 댓글 작성자에 따라 속성을 다르게 출력하게 하였습니다. ("my" : 자신이 작성한 댓글, "other" : 다른 사람이 작성한 댓글)
본인의 댓글인 경우 -> 수정, 삭제, 대댓글
다른 사람의 댓글인 경우 -> 신고, 차단, 대댓글

- 좋아요 버튼 클릭 시 버튼 색이 변경되는 함수와 powerMenu의 메뉴를 생성하고 보여주는 함수가 여러 클래스에서 공통적으로 사용되기 때문에 FunctionUtil.kt에 함수로 정의 해놨습니다. 
- edtTextView에 focus가 있는 경우에만 "댓글을 남기는 중..." 메시지를 보여주게 하였습니다. edtTextView가 아닌 다른 곳을 클릭했을 경우에는 edtTextView의 focus를 제거하여 메시지를 안보이게 하였습니다. 
- Fragment 간의 이동을 구현하기 위해서 jetpack navigation을 적용하였습니다. 

## 📸 스크린샷
|스크린샷|
|https://github.com/ShyPolarBear/Android/assets/107917980/f4c39d28-01f6-4367-882b-ae2268e05193|

|파일첨부바람|

## 📮 관련 이슈
- Resolved: #29

2023-07-13 07:05 UTC, jinukeu requested changes

2023-07-13 07:05 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
> +                else -> binding.cardviewFeedCommentWritingMsg.isVisible = false
binding.cardviewFeedCommentWritingMsg.isVisible = isFocus
로 하는건 어떨까요? (취향 차이 같네요)

2023-07-13 07:05 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +    private val viewLifeCycleOwner: LifecycleOwner,
viewLifeCycleOwner에 대한 의존성 제거 가능해보입니다

2023-07-13 07:05 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
>          binding.ivFeedPostProperty.setOnClickListener {
setOnClickListener가 실행되었을때 동작시킬 함수를 고차함수로 빼주세요

2023-07-13 07:05 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
>          binding.ivFeedPostProperty.setOnClickListener {
```kotlin
class MyGatheringsViewHolder(
    private val binding: LayoutRecyclerMyGatheringContentBinding,
    private val onContentClick: (plubbingId: Int) -> Unit = { },
    private val onMyGatheringMeatBallClick: (view: View, plubbingId: Int) -> Unit = { _, _ -> },
    private val onMyHostingMeatBallClick: (view: View, plubbingId: Int) -> Unit = { _, _ -> },
) : RecyclerView.ViewHolder(binding.root) {

init {
        binding.root.onThrottleClick {
            plubbingId?.let {
                onContentClick(it)
            }
        }

        binding.imageViewMeatBall.onThrottleClick { view ->
            plubbingId?.let { id ->
                onMyGatheringMeatBallClick(view, id)
                onMyHostingMeatBallClick(view, id)
            }
        }
    }
```

힌트입니다

2023-07-13 07:05 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/adapter/FeedPostAdapter.kt
> +    private val viewLifeCycleOwner: LifecycleOwner
viewLifeCycleOwner 의존성 제거 가능해요

2023-07-13 07:05 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
> +                    binding.ivFeedCommentNormalProperty.setMenu(
setMenu 부분을 부모 Fragment에서 하는게 좋아보입니다. (고차 함수 사용)

2023-07-13 07:05 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/viewholder/FeedPostViewHolder.kt
> +        binding.layoutMoveToDetailArea.setOnClickListener {
이 부분도 고차함수로 처리해주세요

2023-07-14 16:02 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/adapter/FeedPostAdapter.kt
> +    private val viewLifeCycleOwner: LifecycleOwner
Hilt 사용하는 것을 말하시는건가요??

2023-07-15 02:39 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/adapter/FeedPostAdapter.kt
> +    private val viewLifeCycleOwner: LifecycleOwner
아 아뇨 
```kotlin
class FeedPostAdapter()
```

이렇게 가능해요

2023-07-16 12:16 UTC, BEEEAM-J commented
피드백 전부 반영하였습니다!

2023-07-16 12:21 UTC, jinukeu approved these changes
💯

2023-07-16 13:05 UTC, kimmandoo approved these changes
고생하셨습니다!! 몇 개 배워가요

2023-07-16 16:05 UTC, merged