[WBS-144]Feature/create kakao login
ShyPolarBear/Android pull request #33
Opened 2023-07-13 13:54 UTC by kimmandoo

## 📌 PR 요약

🌱 작업한 내용
- 카카오 로그인 구현입니다.

🌱 PR 포인트
- api key 숨기기 용도로 secrets gradle plugin 추가했습니다.
- 카카오 로그인 구현
- 카카오 로그인 관련함수를 viewModel 파일 안에 넣어서 사용하려고했는데 context를 사용하고 있어서 기존 fragment파일에 함수를 추가했습니다.
- 멀티모듈로 retrofit 연결하려니까 눈이 좀 어지러워서 잘못된 부분이 많을 것 같습니다. 보이는대로 지적해주시고 고쳐나가겠습니다

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #31

2023-07-13 14:45 UTC, jinukeu requested changes

2023-07-13 14:45 UTC, lluke0 commented on app/src/main/java/com/shypolarbear/android/di/NetworkModule.kt
> +    const val BASEURL = "http://3.37.80.247:8080/"
BASE_URL로 이름 변경 부탁드릴게요

2023-07-13 14:45 UTC, jinukeu commented on build.gradle.kts
> +        classpath("com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:${Versions.SECRETS_GRADLE}")
혹시 이건 어떤 용도인가요?

2023-07-13 14:45 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/LoginFragment.kt
> +                Timber.tag("KAKAO").e(error, getString(R.string.kakao_ac_login_fail))
로그에서 까지 굳이 R 을 사용하지 않아도 될 것 같아요!

2023-07-13 14:45 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/LoginFragment.kt
>                  job.await()
async, await 없어도 잘 동작하지 않나요?

2023-07-13 14:56 UTC, kimmandoo commented on build.gradle.kts
> +        classpath("com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:${Versions.SECRETS_GRADLE}")
local.properties에 적힌 변수를 manifest파일에서 바로 사용할 수 있게 도와주는 라이브러리입니다. api key 쓸때 사용했는데 github에 올릴 때만 사용하라고 해서 나중에 배포할 때는 다른 방법으로 api key를 숨겨야 될 것 같아요

2023-07-13 15:00 UTC, jinukeu commented on build.gradle.kts
> +        classpath("com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin:${Versions.SECRETS_GRADLE}")
사이드 프로젝트 단에서는 github에만 api key를 올리지 않아도 충분한 것 같아요.
지금 이 방식 유지하면 될 것 같습니다!

2023-07-18 08:58 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/LoginFragment.kt
>                  job.await()
await로 기다리면서 그동안 progress bar 작동시키려고 넣어뒀는데 혹시 다른 방법이 있을까요?

2023-07-18 09:09 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/LoginFragment.kt
>                  job.await()
kakaoLogin 메서드가 코루틴 인가요?

2023-07-18 09:21 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/LoginFragment.kt
>                  job.await()
아뇨 코루틴은 아닙니다. suspend로 바꾸고 async를 떼는 게 나을까요?

2023-07-18 09:24 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/LoginFragment.kt
>                  job.await()
지금 의도한건 await로 stateCodeLogIn 값을 받아 회원가입페이지로 보낼지/ 메인페이지로 보낼지 분기하려고 합니다

2023-07-19 11:42 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/LoginFragment.kt
>                  job.await()
```kotlin
val job = async {
                    stateCodeLogIn = kakaoLogin(requireContext())
                }
                job.await()
```

```kotlin
stateCodeLogIn = kakaoLogin(requireContext())
```

이렇게 바꿔도 잘 동작할 것 같네요 아마 ... ? 일단 이렇게 냅두시고 부끄북극 api 나오면 한번 테스트 해보시죠

2023-07-19 11:48 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/LoginFragment.kt
>                  job.await()
그럼 일단 빼는 걸로 수정했습니다!

2023-07-20 11:13 UTC, jinukeu requested changes

2023-07-20 11:13 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/AuthCodeHandlerActivity.kt
> +class AuthCodeHandlerActivity: AppCompatActivity()
이거 Activity 없어도 되지 않나요?

2023-07-20 12:38 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/login/AuthCodeHandlerActivity.kt
> +class AuthCodeHandlerActivity: AppCompatActivity()
수정사항 반영해서 올렸습니다!

2023-07-20 12:39 UTC, jinukeu approved these changes

2023-07-20 14:59 UTC, BEEEAM-J approved these changes

2023-07-20 15:01 UTC, merged