[WBS-145]Feature/create sign up logic
ShyPolarBear/Android pull request #38
Opened 2023-07-30 09:28 UTC by kimmandoo

## 📌 PR 요약

🌱 작업한 내용
- 회원가입 전체 로직(서버로 연동 제외)

🌱 PR 포인트
- 정규식으로 휴대폰번호에서 - 지워서 변수에 넣기, 이메일 필터링
- PickVisualMediaRequest를 이용해서 앨범의 사진을 가져와 Uri로 받음.
- 주요 Ui구현 완료

## 📸 스크린샷
|스크린샷|
|:

https://github.com/ShyPolarBear/Android/assets/46841652/a7016cc3-fb87-448b-b82d-2fbb922224ed

--:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #37

2023-07-30 10:47 UTC, jinukeu requested changes

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +        var mail: String = ""
이런 변수들은 ViewModel에서 관리하는게 좋아
화면 전환과 같은 Configuration Change가 발생하면 전부 초기화 되기 때문!

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +                val goNextState: Boolean = resName.length in 2..8
2..8
이거 상수로 바꾸는게 어떨까

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +                isComplete[1] = goNextState
1 이거 상수로 바꿔줘

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +                    0 -> if (isComplete[0]) {
0, 1, 2 전부 상수로 바꾸거나 enum class 사용하자

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupViewModel.kt
> +    fun getTermData(): LiveData<Boolean> {
이거 너무 자바 같아
유데미 강의에서 한 것 처럼 바꾸는게 어때

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupMailFragment.kt
> +    val emailPattern = Regex("[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}")
문자열 상수로 빼는게 좋아보여
상수로 빼놓으면 내 정보 수정 페이지에서도 같은 문자열 쉽게 사용가능하니까

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupMailFragment.kt
> +            etSignupMail.addTextChangedListener ( object : TextWatcher {
addTextChangedListener 이 부분 확장 함수로 빼내볼래?

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupMailFragment.kt
> +            etSignupMail.addTextChangedListener ( object : TextWatcher {
```kotlin
fun EditText.afterTextChanged(method: (editable: Editable?) -> Unit) {
    addTextChangedListener(object : TextWatcher {
        override fun beforeTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {

        }

        override fun onTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {

        }

        override fun afterTextChanged(p0: Editable?) {
            method(p0)
        }
    })
}
```

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupMailFragment.kt
> +                        sendData(match.value)
그냥 바로 viewModel.sendData 하는게 더 좋을듯?

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupMailFragment.kt
> +                    if (match != null) {
```
match?.let { ... }
```

코틀린 스럽게 바꿔보는거 어때

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
> +                registerForActivityResult(ActivityResultContracts.PickVisualMedia()) { uri ->
오 이건 처음보네 문서 첨부 가능할까?

그리고 전역 변수로 선언하는게 접근성이 더 좋아보여

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
> +                    if (uri != null) {
마찬가지로 uri?.let ...

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
> +                            .into(ivSignupNameProfile)
GlideUtil을 만드는건 어때

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
> +                            .into(ivSignupNameProfile)
```kotlin
object GlideUtil {
    fun loadImage(context: Context, url: String, view: ImageView) {
        load(context, url, view)
    }

    fun loadImage(context: Context, url: String, view: ImageView, placeHolder: Int) {
        load(context, url, view, placeHolder)
    }

    fun loadImage(
        context: Context,
        url: String,
        view: ImageView,
        listener: RequestListener<Drawable>
    ) {
        load(context, url, view, listener = listener)
    }

    fun loadImage(context: Context, file: File, view: ImageView) {
        load(context, file, view)
    }
```

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
> +                if (event != null && event.action == KeyEvent.ACTION_DOWN && event.keyCode == KeyEvent.KEYCODE_ENTER) {
이거 똑같은 코드 많이 보이는데 한번 중복 제거해볼래?

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupTermsFragment.kt
> +                        for ((idx, i) in checkList.withIndex()) {
idx, i 변수명 다시 지어줘

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupTermsFragment.kt
> +                        for ((idx, i) in checkList.withIndex()) {
setOnCheckedChange 이벤트가 발생할때마다 setOnClickListener를 달아주고 있는데, setOnClickListener를 달아주는 동작은 한번이면 충분하지 않아?

2023-07-30 10:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupTermsFragment.kt
> +                if (isChecked) {
아래에 공통된 부분이 많아 보이는데, 중복 제거 해봐

2023-07-30 14:01 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +                    0 -> if (isComplete[0]) {
SignupFragment.kt파일 수정했습니다~

2023-07-31 15:26 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
> +                registerForActivityResult(ActivityResultContracts.PickVisualMedia()) { uri ->
https://developer.android.com/training/data-storage/shared/photopicker?hl=ko&authuser=1

PR 수정사항 반영 완료했어
근데 이게 미디어를 선택하고 나서 이미지 선택창이 꺼져야 콜백이 돌아오는데 전역변수로 선언이 가능할까??

2023-08-01 02:31 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
> +                registerForActivityResult(ActivityResultContracts.PickVisualMedia()) { uri ->
엉 될거야 아마 시도해봐

2023-08-01 09:19 UTC, kimmandoo commented
pickMedia위치 수정했습니다~

2023-08-01 13:55 UTC, jinukeu requested changes

2023-08-01 13:55 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
>                          if (false !in isComplete) {
https://notepad96.tistory.com/80

kotlin의 any 써보는거 어떤가요? (이번주 코틀린 인 액션 스터디에 관련 내용 나와요)

2023-08-01 13:55 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +    private val isComplete = arrayListOf(false, false, false, false)
마찬가지로 configuration change 발생하면 전부 fase로 다시 초기화 되기 때문에 viewModel로 빼는게 좋을 것 같아요

2023-08-01 13:55 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +    private var pageIndex = 1
마찬가지로 configuration change 발생하면 전부 fase로 다시 초기화 되기 때문에 viewModel로 빼는게 좋을 것 같아요

2023-08-01 13:55 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +    private lateinit var btnTv: TextView
아래 코드를 보니 binding.~~~ 를 통해서도 충분히 접근 가능한데 굳이 전역 변수로 뺀 이유가 있나요?

2023-08-01 13:55 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +            }
이 부분 잘 이해가 안가요 설명 가능한가요?

2023-08-01 13:55 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
>                      }
```kotlin
override fun afterTextChanged(s: Editable?) {
                    when {
                        s != null && s.length !in 2..8 -> {
                        s != null && s.length !in NAME_RANGE -> {
                            tvSignupNameRule.text = getString(R.string.singup_error_text)
                            tvSignupNameRule.setTextColorById(requireContext(), R.color.Error_01)
                            
                        }

                        s.isNullOrEmpty() -> {
                            tvSignupNameRule.text = getString(R.string.signup_name_rule)
                            tvSignupNameRule.setTextColorById(requireContext(), R.color.Blue_02)
                            
                        }

                        else -> {
                            tvSignupNameRule.text = getString(R.string.signup_confirm_text)
                            tvSignupNameRule.setTextColorById(requireContext(), R.color.Success_01)
                            
                        }
                        viewModel.setNameData(s.toString())
                    }
                    
                    ```

2023-08-01 13:55 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupNameFragment.kt
>                      }
viewModel.setNameData(s.toString())

가장 바깥으로 빼면 한번만 써도 되지 않을까요?

2023-08-01 13:55 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/pages/SignupPhoneFragment.kt
> +                s?.let {
s?.let 빼도 동일하게 동작할 것 같아요
+ 아래 13 이라는 숫자도 상수로 표기하면 더 이해하기 쉬울 것 같아요

2023-08-01 15:44 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
>                          if (false !in isComplete) {
List 내 원소가 모두 true면 돼서 all로 대체했습니다!

2023-08-01 16:01 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +            }
```kotlin
if (viewModel.pageState[currentItem]) {
//전체페이지 수를 안넘게 해서 마지막 페이지가 아닐때만 if문이 참이 됩니다. 
//현재페이지로 이동할때 currentItem이 이전페이지를 가리키고 있고, 
//현재페이지에서 한번 더 누르면 currentItem이 현재 페이지를 가리키고 있습니다. 
//이 메서드는 다음페이지로 넘어갈때만 호출되므로 다음버튼이 2번 눌려 currentItem이 현재페이지를 출력하더라도 영향을 끼치지 않습니다.
            if (currentItem < binding.signupViewpager.adapter!!.itemCount.minus(1)) {
                // currentItem이 현재 페이지 -1을 출력하고 있고 시작값이 0이라 +2를 하면 지금 보고있는 페이지의 번호가 됩니다.
                viewModel.setPageIndex(currentItem + 2)
                binding.signupIndicator.text = getString(R.string.signup_page_indicator, viewModel.pageIndex.value)
                binding.signupViewpager.setCurrentItem(currentItem + 1, true) // 다음페이지로 넘기면서 smoothScroll을 true로 한 코드입니다.
                updateButtonState(viewModel.pageState[currentItem + 1]) // 다음페이지의 상태를 받아 "다음"버튼의 active여부를 결정합니다.
                // currentItem값이 현재페이지 - 1 이므로 아래코드는 마지막페이지의 "다음"을 "가입 완료"로 바꾸는 코드입니다.
                if(currentItem == Page.PHONE.page) binding.signupTvNext.text = getString(R.string.signup_complete)
            }
        }
```

2023-08-02 09:09 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +            }
`현재페이지에서 한번 더 누르면 currentItem이 현재 페이지를 가리키고 있습니다. `

현재 페이지에서 한번 더 누르면 다음 페이지로 이동해야하는거 아닌가요?

2023-08-02 09:15 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +            }
다음버튼이 활성화되지않으면 해당 메서드 호출이 안돼서 currentItem값을 가져오지않아 저 코드에서 사용하는 currentItem은 항상 이전페이지입니다

2023-08-02 09:27 UTC, jinukeu requested changes

2023-08-02 09:27 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +            }
viewModel.setPageIndex(currentItem + 2)
viewModel의 pageIndex값과 currentItem 값을 서로 동일하게 하는건 어떤가요?

보통 다음 페이지로 넘어가기 위해서는 +1을 해준다고 생각하는데, 어디에서는 +2를 해주고 어디에서는 +1을 해주니 코드 가독성이 너무 떨어지는 것 같아요

2023-08-02 10:07 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +            }
```
if (currentItem < binding.signupViewpager.adapter!!.itemCount.minus(1)) {
                viewModel.setPageIndex(viewModel.pageIndex.value!! + 1)
                binding.signupIndicator.text = getString(R.string.signup_page_indicator, viewModel.pageIndex.value)
                binding.signupViewpager.setCurrentItem(currentItem + 1, true)
                updateButtonState(viewModel.pageState[currentItem + 1])
                if(currentItem == Page.PHONE.page) binding.signupTvNext.text = getString(R.string.signup_complete)
            }
```

이렇게 바꿔봤는데 어떤가요?

2023-08-02 11:11 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +            }
오 훨씬 낫네요

viewModel.setPageIndex(viewModel.pageIndex.value!! + 1)
viewModel.pageIndex.value!! + 1 이 파라미터 아예 없앨 수 있을거같아요 없애주세요!

2023-08-02 11:26 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/signup/SignupFragment.kt
> +            }
viewModel에서 연산하는 방식으로 제거했습니다

2023-08-02 13:33 UTC, kimmandoo commented
수정사항 모두 반영했습니다~

2023-08-02 15:02 UTC, jinukeu approved these changes
💯

2023-08-02 15:40 UTC, BEEEAM-J reviewed
몰랐던 것들 많이 알아가네요 고생하셨습니다~!

2023-08-02 15:40 UTC, BEEEAM-J approved these changes

2023-08-02 15:42 UTC, merged