[WBS-150]Feature/apply mock test data
ShyPolarBear/Android pull request #39
Opened 2023-07-30 10:15 UTC by BEEEAM-J

## 📌 PR 요약

🌱 작업한 내용
- mock 서버에서 받아온 데이터를 화면에 보여주는 동작 추가
- 네트워크 호출 시 오류 확인 쉽게 하기 위해서 Network Module 수정
- BaseActivity 수정

🌱 PR 포인트
- 대부분의 작업들은 기존의 동작을 서버에서 받아온 데이터를 적용하도록 변경한 작업입니다.
- 기존에 댓글은 한 개의 recyclerView를 사용하여 구현 하였지만 댓글 model에 맞게 중첩 recyclerView를 사용하여 구현 하였습니다.
- recyclerView viewHolder의 bind 함수 내에서 리스너 작업을 하면 성능 저하 이슈가 있기 때문에 모든 리스너 작업을 init에서 처리하도록 수정하였습니다.
- BaseActivity의 preLoad 함수는 스플래시 화면을 로딩할 때만 사용되기 때문에 BaseActivity에 없어도 된다고 판단하여 제거하였습니다.
- SampleRepoImpl을 참고하여 작성된 모든 RepoImpl들에서 서버에 동일한 요청을 두 번하는 문제를 찾아서 한 번만 요청하는 것으로 수정하였습니다. 
- uiState는 다음 이슈에서 처리할 예정입니다.

## 📸 스크린샷
|스크린샷|
https://github.com/ShyPolarBear/Android/assets/107917980/4454184d-dd01-4a5a-9bc0-d0509dfd24b4
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #36

2023-07-30 11:01 UTC, jinukeu requested changes

2023-07-30 11:01 UTC, lluke0 commented on data/src/main/java/com/shypolarbear/data/api/feed/FeedApi.kt
> +        @Path("feedId", encoded = true) feedID: Int
encoded = true로 한 이유가 있을까

2023-07-30 11:01 UTC, lluke0 commented on domain/src/main/java/com/shypolarbear/domain/model/feed/FeedTotal.kt
> +    val `data`: Data,
``를 넣은 이유?

2023-07-30 11:01 UTC, lluke0 commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedUseCase.kt
> +class FeedUseCase(
UseCase는 하나의 일만 하는게 좋아

2023-07-30 11:01 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
> +        viewModel.loadFeedDetail(requireArguments().getString(FEED_ID)!!.toInt())
safeArgs 사용해봐

2023-07-30 11:01 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
> +        if (feedDetail.authorProfileImage != "") {
isNotBlank()

2023-07-30 11:01 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
> +                true -> {
false 일때랑 동일한 부분이 많은데 중복 제거해봐

2023-07-30 11:01 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/adapter/FeedCommentAdapter.kt
> +            0
enum class로 만드는거 어때?

2023-07-30 11:01 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/adapter/FeedReplyAdapter.kt
> +            0
enum class 좀 더 활용 ㄱㄱ

2023-07-30 11:01 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
> +        var btnClicked = false
이건 어디에 쓰는거야?

2023-07-30 11:01 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
> +    private var co: Comment = Comment()
co 변수명 너무 안좋아 좀 더 구체적으로 바꿔줘

2023-07-30 11:01 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedTotal/FeedTotalFragment.kt
> +            FEED_ID to feedId.toString()
safeArgs 사용해봐

2023-07-30 11:01 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/util/FunctionUtil.kt
> +fun Button.showLike(isLike: Boolean, view: Button) {
함수명 더 구체적으로 바꿔줘

2023-07-30 11:01 UTC, jinukeu commented on presentation/src/main/res/layout/fragment_feed_detail.xml
> +                    app:shapeAppearanceOverlay="@style/Radius24"
Radius24 -> radius_24

2023-07-30 16:34 UTC, BEEEAM-J commented on data/src/main/java/com/shypolarbear/data/api/feed/FeedApi.kt
> +        @Path("feedId", encoded = true) feedID: Int
예전에 사용할 때도 이렇게 했었어서... 근데 찾아보니까 빼도 되는거 같아서 제거 했어

2023-07-30 16:44 UTC, BEEEAM-J commented on domain/src/main/java/com/shypolarbear/domain/model/feed/FeedTotal.kt
> +    val `data`: Data,
kotlin data class File from JSON으로 예시 Json을 넣어서 생성해서 꼭 있어야 되는 줄 알았는데 빼고 테스트 해보니까 잘되서 제거했어

2023-07-30 16:47 UTC, BEEEAM-J commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedUseCase.kt
> +class FeedUseCase(
그럼 repository도 하나의 일만 하는게 좋나??

2023-07-30 17:50 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
> +        if (feedDetail.authorProfileImage != "") {
isNotBlank()로 처리하면 에러떠서 
``` !feedDetail.authorProfileImage.isNullOrBlank() ```
이렇게 수정했는데 괜찮나?

2023-07-30 18:18 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
> +        var btnClicked = false
좋아요 버튼이 한 번이라도 클릭 되었는지 확인하려고 넣었어
좋아요 버튼이 클릭 되었을 때 이 버튼이 한 번이라도 클릭 되었었는지 확인해서 클릭 된 적이 없으면 bind 함수에서 받아온 댓글 정보로 버튼 상태 초기화 하고, 클릭 된 적이 있으면 이전 버튼 상태로 초기화 할 때 사용 돼

2023-07-31 02:17 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
> +        if (feedDetail.authorProfileImage != "") {
엉 괜춘괜춘

2023-07-31 02:25 UTC, jinukeu commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedUseCase.kt
> +class FeedUseCase(
https://mashup-android.vercel.app/mashup-11th/heejin/useCase/useCase/

UseCase의 이름만 보고도 어떤 동작이 수행되는지 한눈에 파악하기 위해 UseCase는 한번에 하나의 일만 해
(하나의 UseCase가 여러 동작을 수행한다면 UseCase의 이름만 보고 어떤 동작을 수행하는지 명확하게 파악할 수 없음)

Repository는 데이터 접근이 어떻게 되는지 추상화 해주는 역할이라서 여러 개의 일을 해도 좋을 것 같네

2023-07-31 02:28 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
> +        var btnClicked = false
Comment 객체의 isCommentLike를 통해서도 버튼 클릭 여부를 확인할 수 있지 않아?

2023-07-31 08:33 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
> +        var btnClicked = false
음... 어떤 방식으로???

2023-07-31 08:45 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
> +        var btnClicked = false
지금 좋아요 버튼을 누르면 View의 상태만 업데이트를 해주고 있어

예를 들어 3번째 댓글의 좋아요를 누르게 되면 눈에 보이는 View의 상태는 좋아요가 눌린 것으로 바뀌지만

ViewModel에 있는
`val feedComment: LiveData<List<Comment>> = _feedComment`의 3번째 Comment 객체에는 좋아요가 눌려있지 않아

이렇게되면 발생하는 문제는 
1. 화면 전환과 같은 Configuration Change가 발생해 RecyclerView가 새로 그려지는 경우, feedComment의 데이터를 기반으로 그려지기 때문에 좋아요가 눌리지 않은 상태로 복원
2. 리사이클러뷰의 아이템이 다시 bind 된다면 좋아요가 눌리지 않는 상태로 복원

2023-07-31 08:46 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/viewholder/FeedCommentNormalViewHolder.kt
> +        var btnClicked = false
좋아요 버튼을 누르면 feedComment의 값을 업데이트해서 좋아요가 눌렀다는걸 반영해야해

2023-08-07 09:47 UTC, BEEEAM-J commented
피드백 모두 반영하였습니다!

2023-08-07 10:46 UTC, jinukeu requested changes

2023-08-07 10:46 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
>              }.attach()
이건 어떤 용도인가요? 값이 비어있어서 여쭤봅니다!

2023-08-07 10:46 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedTotal/viewholder/FeedPostViewHolder.kt
>              }.attach()
위 코멘트와 동일

2023-08-07 11:34 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
>              }.attach()
사용하지 않는 변수라서 이름을 변경한 것인데 사용하는 정확한 이유는 잘 모르겠습니다...

2023-08-07 11:38 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
>              }.attach()
필요없어보이네요?
한번 지워보시고 ... 이게 어떤 걸 하는 건지 알아본 후 코멘트로 알려주세요 ~ 무지성 복붙 코드는 안됩니다

2023-08-07 11:39 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
>              }.attach()
네 알겠습니다....!!

2023-08-07 18:29 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedDetail/FeedDetailFragment.kt
>              }.attach()
ViewPager와 TabLayout을 연결하는데 TabLayoutMediator를 사용합니다. 첫 번째 인자는 tabLayout이고 두 번째 인자는 tabLayout의 위치입니다. TabLayoutMediator의 람다의 인자가 TabLayout.Tab, Int 필요해서 제거할 수 없습니다. 해당 인자들은 위치에 따른 tabLayout의 동작을 설정할 때 사용하는데 현재 피드에서 사용되는 tabLayout은 단순히 이미지를 보여주는 용도로 쓰이기 때문에 함수의 본문을 비워도 된다고 생각합니다..!

2023-08-07 23:35 UTC, jinukeu approved these changes

2023-08-08 08:14 UTC, kimmandoo approved these changes
네트워크 모듈 사용 배워갑니다

2023-08-08 10:36 UTC, merged