[WBS-188]Feature/sync sign up api
ShyPolarBear/Android pull request #55
Opened 2023-08-22 10:00 UTC by kimmandoo

## 📌 PR 요약

🌱 작업한 내용
- 회원가입 API 연동
- DataStore 적용

🌱 PR 포인트
- 회원가입 입력정보를 서버에 넘기고, 응답을 받습니다.
- 지금 가입을 미리 해둔 상태라 이미 가입했다고 토스트메시지로 나옵니다. 미가입자면 지정해둔 페이지(현재 feed로 지정됨)로 이동합니다.
- DataStore를 이용해 서버로 응답받은 accessToken, refreshToken을 저장합니다.(저장하고 불러오는 것까지 확인했습니다)
- 영상으로 흘러가는 흐름이 맞는지 확인 부탁드립니다.
- NormalRetrofit의 URL을 BASE_URL로 수정했습니다.

## 📸 스크린샷
|스크린샷|
|:-

https://github.com/ShyPolarBear/Android/assets/46841652/d6319681-9e68-439b-9282-a63d7ec7fdef

-:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #51

2023-08-22 11:10 UTC, jinukeu commented
회원가입 맨 마지막에 카카오 로그인을 진행하지 마시구,
1. 카카오 로그인 진행
2. 카카오 로그인 성공 후 부끄북극 회원가입 진행

이렇게 해주세요!

카카오 로그인을 먼저해서, 이미 가입된 유저라면 바로 홈 화면으로 이동하고 그렇지 않다면 회원가입을 진행하는 플로우가 맞아요~!

2023-08-22 11:18 UTC, jinukeu requested changes

2023-08-22 11:18 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/join/JoinFragment.kt
> +        }
ac, re token
UseCase를 통해 받아와주세요

뷰에는 data 관련 로직이 없는게 좋습니다.
Repository 패턴에 대해 더 공부하시면 좋을거같아요!

2023-08-22 11:18 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/join/JoinFragment.kt
> +                    }
뷰에서 토큰 저장하면 안됩니다!

2023-08-22 12:22 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/join/JoinFragment.kt
> +        }
아 이건 사용하지않고 기록만 해둔거라 지우면 됩니다!

2023-08-26 15:23 UTC, kimmandoo commented
PR사항 반영했습니다. 시간이 늦어서 낮에 노을님에게 말씀드리고 신규 회원가입 진행하겠습니다!

2023-08-26 15:35 UTC, jinukeu approved these changes
👍

2023-08-26 15:59 UTC, kimmandoo commented
수정완료했습니다!

2023-08-26 17:22 UTC, BEEEAM-J approved these changes
고생하셨슴돠~~~ 👍

2023-08-27 06:27 UTC, merged