[WBS-193]Feature/add feed write UI
ShyPolarBear/Android pull request #56
Opened 2023-08-23 09:56 UTC by BEEEAM-J

## 📌 PR 요약

🌱 작업한 내용
- 피드 작성 UI 구현
- 피드 전체 조회에서 피드 작성으로 이동 구현
- PickVisualMediaRequest 사용하여 갤러리 내의 이미지를 uri 리스트로 받아오게 구현
- x버튼 누르면 업로드할 이미지를 리스트에서 제거

🌱 PR 포인트
- 피드 작성 UI 및 피드 전체 조회 화면과 연결을 구현하였습니다. 화면 죄측 상단의 < 버튼 클릭 시 이전 화면으로 이동하게 하였고, 제목과 내용 중 하나라도 빈 값이 있는 경우 게시물 작성되서 이전 화면으로 이동하지 못하게 하였습니다.
- PickVisualMediaRequest를 사용하여 갤러리 내의 이미지를 업로드할 수 있게 하였습니다. 한 번에 여러 장을 업로드 할 수 있게 하였고, 한 번에 최대 5장까지 선택할 수 있게 하였습니다. 추가로 선택한 이미지가 이미 5장인 경우, 이미 선택된 이미지에 추가로 선택한 이미지가 5장이 넘어가는 경우에는 토스트 메시지를 띄우면서 이미지를 리스트에 넣지 못하게 했습니다.

## 📸 스크린샷
|스크린샷|
https://github.com/ShyPolarBear/Android/assets/107917980/2cc4671b-d690-45de-af27-61a615f98970
(에뮬레이터에서는 PickVisualMediaRequest의 PickMultipleVisualMedia모드가 실행이 안되서 실기기로 테스트했슴다 ㅎㅎ)
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #54

2023-08-23 16:06 UTC, jinukeu commented
코멘트 테스트

2023-08-23 16:06 UTC, jinukeu commented
에뮬레이터 api 수준 몇인가요? 30?

2023-08-23 16:12 UTC, BEEEAM-J commented
> 에뮬레이터 api 수준 몇인가요? 30?

31입니다!

2023-08-23 16:13 UTC, lluke0 commented
> > 에뮬레이터 api 수준 몇인가요? 30?
> 
> 31입니다!

음 구체적으로 어떤 이슈가 발생하면서 photo picker가 실행되지 않았나요?

2023-08-23 16:16 UTC, BEEEAM-J commented
> > > 에뮬레이터 api 수준 몇인가요? 30?
> > 
> > 
> > 31입니다!
> 
> 음 구체적으로 어떤 이슈가 발생하면서 photo picker가 실행되지 않았나요?

아뇨 아뇨 실기기에서 테스트할 때와 달리 바텀 시트로 갤러리의 이미지 선택창이 나오지 않고 바로 갤러리로 넘어가집니다. 그리고 이미지를 클릭하면 하나만 선택이 됩니다.

2023-08-23 16:21 UTC, jinukeu commented
https://developer.android.com/training/data-storage/shared/photopicker

If the photo picker isn't available on a device, the library automatically invokes the [ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/kotlin/android/content/Intent#action_open_document) intent action instead. This intent is supported on devices that run Android 4.4 (API level 19) or higher. You can verify whether the photo picker is available on a given device by calling [isPhotoPickerAvailable()](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia#isPhotoPickerAvailable(android.content.Context)).

느낌이 이거 같긴한데 ... `[isPhotoPickerAvailable()](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia#isPhotoPickerAvailable(android.content.Context))` 로 체크한번 해보시겠어요?

https://developer.android.com/training/data-storage/shared/photopicker#device-availability
api 31이면 백포팅 안해도 될텐데 미스테리군요 ...

2023-08-23 16:32 UTC, BEEEAM-J commented
> https://developer.android.com/training/data-storage/shared/photopicker
> 
> If the photo picker isn't available on a device, the library automatically invokes the [ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/kotlin/android/content/Intent#action_open_document) intent action instead. This intent is supported on devices that run Android 4.4 (API level 19) or higher. You can verify whether the photo picker is available on a given device by calling [isPhotoPickerAvailable()](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia#isPhotoPickerAvailable(android.content.Context)).
> 
> 느낌이 이거 같긴한데 ... `[isPhotoPickerAvailable()](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia#isPhotoPickerAvailable(android.content.Context))` 로 체크한번 해보시겠어요?
> 
> https://developer.android.com/training/data-storage/shared/photopicker#device-availability api 31이면 백포팅 안해도 될텐데 미스테리군요 ...

맞네요 로그 찍어봤는데 false 나오네요...ㅎ

2023-08-24 02:21 UTC, jinukeu commented
> > https://developer.android.com/training/data-storage/shared/photopicker
> > If the photo picker isn't available on a device, the library automatically invokes the [ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/kotlin/android/content/Intent#action_open_document) intent action instead. This intent is supported on devices that run Android 4.4 (API level 19) or higher. You can verify whether the photo picker is available on a given device by calling [isPhotoPickerAvailable()](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia#isPhotoPickerAvailable(android.content.Context)).
> > 느낌이 이거 같긴한데 ... `[isPhotoPickerAvailable()](https://developer.android.com/reference/kotlin/androidx/activity/result/contract/ActivityResultContracts.PickVisualMedia#isPhotoPickerAvailable(android.content.Context))` 로 체크한번 해보시겠어요?
> > https://developer.android.com/training/data-storage/shared/photopicker#device-availability api 31이면 백포팅 안해도 될텐데 미스테리군요 ...
> 
> 맞네요 로그 찍어봤는데 false 나오네요...ㅎ

공식문서 보고 백포팅 설정 한번 해보시겠어요?

2023-08-25 09:26 UTC, jinukeu requested changes

2023-08-25 09:26 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedWrite/FeedWriteFragment.kt
> +
when 쓰는거 어떠세요?

2023-08-25 09:26 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedWrite/FeedWriteViewModel.kt
> +    }
private val _testImgList = MutableLiveData<MutableList<FeedWriteImg>>(mutableListOf())

이렇게 하면 init 블록 없앨 수 있지 않나요?

2023-08-25 09:26 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedWrite/FeedWriteFragment.kt
> +        binding.rvFeedWriteUploadImg.adapter!!.notifyItemRemoved(position)
음 notifyItemRemoved 없이 viewModel.removeImgList 호출만으로도 리사이클러뷰 갱신 가능할거에요

2023-08-25 09:26 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedWrite/FeedWriteViewModel.kt
> +        _testImgList.value!!.removeAt(position)
https://jinsangjin.tistory.com/41

removeAt을 해도 객체의 주소값은 동일하기 때문에 observe가 안될거에요

2023-08-25 10:59 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedWrite/FeedWriteFragment.kt
> +        binding.rvFeedWriteUploadImg.adapter!!.notifyItemRemoved(position)
notifyItemRemoved 제거하고 실행해봤는데 리사이클러뷰 갱신이 안되네요...ㅠ

2023-08-25 11:04 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedWrite/FeedWriteViewModel.kt
> +        _testImgList.value!!.removeAt(position)
removeImgList의 내부 동작 방식을 바꿔야합니다.
물론 해결 코드를 바로 알려드릴 수도 있지만 ... 그건 오히려 범준님의 성장에 독이 되는 행동이기에 힌트만 드리는 점 양해부탁드려요

2023-08-26 13:45 UTC, BEEEAM-J commented
피드백 사항 전부 반영하였습니다~!

2023-08-26 14:39 UTC, jinukeu approved these changes

2023-08-26 14:39 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/feed/feedWrite/FeedWriteFragment.kt
> +                feedWriteImgAdapter.submitList(applyChangeList)
feedWriteImgAdapter.submitList(it.toList())

이렇게 간편화 가능해요 이것만 수정하시구 바로 머지 하시죠~ 고생하셨어요 :)

2023-08-26 15:16 UTC, kimmandoo approved these changes
progressbar 참고가 되네요

2023-08-26 17:04 UTC, merged