[WBS-182]Feature/apply my info api
ShyPolarBear/Android pull request #60
Opened 2023-08-27 17:33 UTC by BEEEAM-J

## 📌 PR 요약

🌱 작업한 내용
- 내 정보 조회, 수정 api 연동

🌱 PR 포인트
- 내 정보 수정 화면으로 전환 시 내 정보 조회 요청을 하여 현재 사용자의 정보를 초기 값으로 보여줍니다. 
- 빈 값이 하나라도 있는 경우, 조건을 충족하지 않는 것이 하나라도 있는 경우가 아니면 내 정보 수정 요청을 할 수 있게 하였습니다.
- 프로필 사진 링크를 보낼 수 없는 상황이기 때문에 내 정보 수정 요청 시 프로필 사진 파트에는 "NULL"이라는 문자열을 보내게 하였습니다. (추후 수정 예정)

## 📸 스크린샷
|스크린샷|
https://github.com/ShyPolarBear/Android/assets/107917980/4488fa28-69ae-48c9-a0d8-8d254bbb2e5a
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #46

2023-08-29 11:21 UTC, jinukeu requested changes

2023-08-29 11:21 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/more/changemyinfo/ChangeMyInfoFragment.kt
> +                    edtChangeMyInfoEmail.text.toString().isNullOrBlank()-> {
listOf(nameState, phoneNumberState, emailState).any { it ==InputState.OFF  }
listOf(edtChangeMyInfoNickname.text.toString().isNullOrBlank() ~~~).any { it.isNullOrBlank() }

이렇게 바꾸는거 어떠세요?

2023-08-29 16:11 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/more/changemyinfo/ChangeMyInfoFragment.kt
> +                    edtChangeMyInfoEmail.text.toString().isNullOrBlank()-> {
오오 저 부분 코드가 좀 지저분한 거 같아서 거슬렸는데 수정하겠습니다!
listOf(nameState, phoneNumberState, emailState).any { it ==InputState.OFF } ||
                    listOf(edtChangeMyInfoNickname.text.toString(),
                        edtChangeMyInfoPhoneNumber.text.toString(),
                        edtChangeMyInfoEmail.text.toString()).any { it.isNullOrBlank() } -> {
                        // 실행할 코드
                    }
이런 식으로 수정하면 될까요??

2023-08-30 06:08 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/more/changemyinfo/ChangeMyInfoFragment.kt
> +                    edtChangeMyInfoEmail.text.toString().isNullOrBlank()-> {
네 좋아요~

2023-08-30 06:08 UTC, jinukeu approved these changes

2023-08-30 06:12 UTC, kimmandoo approved these changes
👍👍👍👍

2023-08-30 13:31 UTC, merged