[WBS-197]Feature/sync daily quiz api
ShyPolarBear/Android pull request #66
Opened 2023-09-05 12:25 UTC by kimmandoo

## 📌 PR 요약

🌱 작업한 내용
- 퀴즈 API 모두 연동, 구현 완료 했습니다

🌱 PR 포인트
- ProgressBar의 부드러움을 위해 프레임을 늘렸더니 실제 시간 측정 시 16.3초 정도가 나옵니다. 이 부분은 어떻게 해야할지 고민입니다.
- 복습퀴즈 마지막 페이지에서는 메인 화면으로 보냈습니다.
- ViewPager대신 navgraph에서 self를 활용해서 프래그먼트를 재사용했습니다.
- EventWrapper를 추가했습니다. 한번 호출한 viewmodel 요소는 peekContent로 접근할 수 있습니다.

## 📸 스크린샷
|스크린샷|
|:-

https://github.com/ShyPolarBear/Android/assets/46841652/cd9ad48c-112e-41cb-ab72-707e349a718f

-:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #57

2023-09-05 12:28 UTC, jinukeu commented
실제 시간 측정 시 16.3초 정도

사이드 프로젝트라서 이 정도 오차는 괜찮지만, 실무라면 15초를 꼭 맞춰야할 것 같아요.
한번 트러블 슈팅 해보시죠 ~

2023-09-05 12:29 UTC, kimmandoo commented
> 실제 시간 측정 시 16.3초 정도
> 
> 사이드 프로젝트라서 이 정도 오차는 괜찮지만, 실무라면 15초를 꼭 맞춰야할 것 같아요. 한번 트러블 슈팅 해보시죠 ~

트레이드오프 지점을 찾아보겠습니다!

2023-09-05 12:31 UTC, jinukeu requested changes

2023-09-05 12:31 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/quiz/QuizViewModel.kt
> +
private val _reviewQuizPage = MutableLiveData<Int>(0)

이렇게 해서 초기값 지정 가능해요

2023-09-06 10:37 UTC, kimmandoo commented
방법을 바꿔서 progressbar 15초에 정확히 맞췄습니다! Timer를 사용했어요

2023-09-06 11:08 UTC, jinukeu requested changes
백그라운드에서도 정상 동작 하나요?

2023-09-06 11:08 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/util/FunctionUtil.kt
> +    val totalTime = 15000L
const로 빼주세요~!

2023-09-06 11:15 UTC, kimmandoo commented
> 백그라운드에서도 정상 동작 하나요?

홈버튼을 눌러 나간 경우에도 정상작동하고 있습니다

2023-09-06 11:16 UTC, jinukeu approved these changes
오오 Timer 는 저도 처음보네요!! 트러블 슈팅 좋았습니다 ㅎㅎ 💯 👍 🥇 
미리 어프로브 할게요!

2023-09-06 17:10 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/util/FunctionUtil.kt
> +                totalProgress -= 1
저 궁금한게 totalProgress -= 1에서 1이 1초를 말하는 건가요?? 아니면 timer.scheduleAtFixedRate 함수가 0.01초 마다 주기적으로 실행되서 1인건가요??
(Timer 처음 접해서 잘 몰라서 질문합니다...ㅎㅎ)
큰 문제 없는 거 같아서 미리 approve 하겠슴다~~!

2023-09-06 17:11 UTC, BEEEAM-J approved these changes
고생하셨습니다~ Timer 배워가용 :)

2023-09-07 04:01 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/util/FunctionUtil.kt
> +                totalProgress -= 1
1초라기 보다는 progressbar 전체 길이가 1500인데 1만큼 줄어드는 코드입니다!  다시보니 버그가 있었는데 덕분에 고쳤습니다!

2023-09-07 04:02 UTC, merged