[WBS-211]Feature/test feed api
ShyPolarBear/Android pull request #69
Opened 2023-09-17 18:01 UTC by BEEEAM-J

## 📌 PR 요약

🌱 작업한 내용
- 이미지 제외 피드 관련 api 모두 적용, 테스트

🌱 PR 포인트
- 전체 피드 조회 화면에 swipe refresh layout을 적용하여 최상단 화면에서 밑으로 스크롤을 하는 경우 새로고침을 할 수 있게 하였습니다.
- 게시물의 이미지 유무에 따라 다른 뷰로 보여주게 하였습니다. 
- 전체 피드 조회 화면을 실행하는 조건을 총 3개로 나누어 처음 실행되는 경우, 게시물 상세 조회 화면에서 되돌아가는 경우에는 전체 피드 데이터를 갱신하고 피드 작성화면에서 되돌아가는 경우에는 그대로 보여주게 하였습니다.
- 무한 스크롤 로직을 화면에 보여주는 마지막 아이템의 위치와 어댑터의 아이템 개수를 비교하는 방식으로 수정하였습니다.

## 📸 스크린샷
|스크린샷|
https://github.com/ShyPolarBear/Android/assets/107917980/17015b0b-d2bc-45e1-a17f-9e1bfbbace13

## 📮 관련 이슈
- Resolved: #65

2023-09-18 03:03 UTC, jinukeu requested changes

2023-09-18 03:03 UTC, jinukeu commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedTotalUseCase.kt
>      }
`operator fun invoke` 사용해주세요!
다른 유즈케이스도 마찬가지입니다.

https://velog.io/@ohzzi/Kotlin-operator-fun-invoke

2023-09-18 07:07 UTC, BEEEAM-J commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedTotalUseCase.kt
>      }
피드백 사항 반영하였습니다!
근데 질문이 있는데 유즈케이스의 메서드를 `operator fun invoke`로 사용하는 것은 단순히 코드의 단순화, 가독성 향상 때문인가요??

2023-09-18 07:09 UTC, jinukeu commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedTotalUseCase.kt
>      }
유즈케이스의 이름만으로도 어떤 일을 하는지 명확하게 파악 가능한데, 굳이 메서드에서도 이름을 적을 필요가 없기 때문이라 생각해요!

말씀하신 코드의 단순화, 가독성 향상 때문이 맞습니다.

2023-09-18 07:11 UTC, BEEEAM-J commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedTotalUseCase.kt
>      }
아하..! 여태 유즈케이스에 따로 메서드를 정의해서 사용했었는데 하나 배워가네요!!

2023-09-18 07:11 UTC, jinukeu requested changes
UseCase 네이밍도 전체적으로 수정해주시면 좋을거같아요!
예시는 몇개 코멘트로 달아놨습니다 ㅎㅎ

2023-09-18 07:11 UTC, jinukeu commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedTotalUseCase.kt
>  class FeedTotalUseCase(
LoadFeedTotalUseCase 어떠세요?

2023-09-18 07:11 UTC, jinukeu commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedDetailUseCase.kt
>  class FeedDetailUseCase (
LoadFeedDetailUseCase가 더 좋아보입니다.

2023-09-18 16:35 UTC, BEEEAM-J commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedDetailUseCase.kt
>  class FeedDetailUseCase (
무언가를 받아오는 동작은 Load~~UseCase로 정의하고 무언가를 요청하는 동작은 Request~~UseCase로 통일 하려는데  어떤가요???

2023-09-19 02:47 UTC, jinukeu commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedDetailUseCase.kt
>  class FeedDetailUseCase (
네 괜찮아보여요

2023-09-19 05:32 UTC, BEEEAM-J commented on domain/src/main/java/com/shypolarbear/domain/usecase/feed/FeedDetailUseCase.kt
>  class FeedDetailUseCase (
수정했습니다~!

2023-09-19 05:32 UTC, jinukeu approved these changes
👍

2023-09-19 07:57 UTC, kimmandoo approved these changes
고생하셨습니다!!

2023-09-19 07:59 UTC, merged