[WBS-219]Feature/create my feed
ShyPolarBear/Android pull request #72
Opened 2023-09-25 05:13 UTC by kimmandoo

## 📌 PR 요약

🌱 작업한 내용
- 내가 작성한 게시글 부분 구현

🌱 PR 포인트
- DiffUtil 콜백으로 list 업데이트를 해줬습니다
- 서버에 아직 데이터가 들어있지않아서 그냥 mockList넣어보면서 테스트 진행했습니다
- delay를 넣는대신에 job.join으로 데이터 로드중 suspend를 넣었습니다
- 무한스크롤 구현이 처음이라 많이 부족합니다 많은 지적 부탁드려요

## 📸 스크린샷
|스크린샷|
|:--:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #71

2023-09-25 05:47 UTC, jinukeu requested changes

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/MyPageFragment.kt
> +                }
@BEEEAM-J 무한스크롤 확장함수로 빼놓은거 없었나요?

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/MyPageFragment.kt
> +    }
ViewModel에서 처리하는게 좋을거같아요

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/MyPageViewModel.kt
> +    val scrollState: LiveData<Boolean> = _scrollState
scrollState는 어떻게 사용되는건가요?

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/adapter/MyPostAdapter.kt
> +class MyPostAdapter(private val _items: List<MyFeed?>, private val context: Context) :
context 없어도 될거같아요.

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/adapter/MyPostAdapter.kt
> +    }
굳이 initPostAdapter을 사용한 이유가 있나요?

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/adapter/MyPostAdapter.kt
> +                GlideUtil.loadImage(context, item.feedImage, ivItemPage)
`context` -> `binding.root.context` 이렇게 바꿀 수 있을거에요.

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/adapter/MyPostAdapter.kt
> +    }
ListAdapter 사용하면 이 로직 필요없어요.

https://cliearl.github.io/posts/android/recyclerview-listadapter/

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/diffutil/MyPostDiffUtilCallback.kt
> +}
RecyclerView의 ListAdapter 적용하면서 바꾸셔야할 것 같아요,

2023-09-25 05:47 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/util/FunctionUtil.kt
> +
invertActivation은 어떤 역할을 하나요?

2023-09-25 05:59 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/MyPageFragment.kt
> +                }
아 있네요 아래 반영사항까지 포함해서 확장함수에 있는걸로 적용하겠습니다

2023-09-25 06:01 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/util/FunctionUtil.kt
> +
게시글, 코멘트 부분 색상 변경용으로 빼뒀는데 지금보니 FunctionUtil에 둘 필요가 없을 것 같네요

2023-09-25 06:03 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/adapter/MyPostAdapter.kt
> +    }
주생성자에 바로 접근하는 대신 팩토리함수처럼 접근하게 해봤습니다. 크게 장점을 모르겠어서 삭제하는 게 나을 것 같네요

2023-09-25 06:04 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/MyPageViewModel.kt
> +    val scrollState: LiveData<Boolean> = _scrollState
스크롤 하단에 닿을 때 데이터 불러오게 하기 위한 트리거용도로 사용했는데 확장함수로 적용하면 필요없어지네요!

2023-09-25 06:19 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/mypage/MyPageFragment.kt
> +                }
@jinukeu FunctionUtil에 infiniteScroll 이라는 이름으로 recyclerView의 확장함수로 정의해놓은거 있습니다!

2023-09-30 13:08 UTC, kimmandoo commented
수정사항 다 반영했습니다!

2023-09-30 14:45 UTC, jinukeu approved these changes
👍

2023-10-01 03:17 UTC, BEEEAM-J approved these changes
고생하셨습니다~!

2023-10-01 07:12 UTC, merged