[WBS-234]Feature/create total ranking
ShyPolarBear/Android pull request #78
Opened 2023-10-11 08:37 UTC by kimmandoo

## 📌 PR 요약

🌱 작업한 내용
- 전체 랭킹 조회 구현
- 전체 랭킹 API 연동
- 내 랭킹 조회 구현
- 내 랭킹 API 연동

🌱 PR 포인트
- 내랭킹/전체랭킹이 겹쳐서 한번에 작업했습니다
- 샘플 상품 url 처리를 어떻게 해야할지가 고민입니다.

## 📸 스크린샷
|스크린샷|
|:-
![Screenshot_1697013290](https://github.com/ShyPolarBear/Android/assets/46841652/e654afa1-9c28-4d7a-bf31-c64b0ca07876)
-:|
|파일첨부바람|

## 📮 관련 이슈
- Resolved: #77

2023-10-11 08:42 UTC, jinukeu requested changes
ListAdapter 사용 시, submitList와 조합해서 사용하는 레퍼런스 찾아보시구 적용하면 완벽해질거같아요!

2023-10-11 08:42 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/ranking/RankingFragment.kt
> +                    val rankingAdapter = RankingAdapter(totalRanking.content)
submitList를 사용하지 않은 이유가 있나요?

2023-10-11 08:42 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/ranking/RankingAdapter.kt
> +class RankingAdapter(private val _items: List<Ranking>) :
submitList를 사용하면 따로 _items 파라미터를 만들 필요가 없습니다!

2023-10-11 08:42 UTC, lluke0 commented on presentation/src/main/java/com/shypolarbear/presentation/ui/ranking/RankingAdapter.kt
> +        return if (_items[position] != null) MyFeedType.ITEM.state else MyFeedType.LOADING.state
submitList 사용하면 currentList를 통해서 현재 아이템들 받아올 수 있어요.

2023-10-11 09:20 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/ranking/RankingFragment.kt
> +                    val rankingAdapter = RankingAdapter(totalRanking.content)
사용 미숙이었습니다.. 수정사항 반영했습니다!

2023-10-11 09:21 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/ranking/RankingFragment.kt
> +                    val rankingAdapter = RankingAdapter(totalRanking.content)
quiz main페이지 고칠때 저번 무한스크롤 작업도 submitList로 수정해둘게요

2023-10-11 10:30 UTC, jinukeu requested changes

2023-10-11 10:30 UTC, jinukeu commented on presentation/src/main/java/com/shypolarbear/presentation/ui/ranking/RankingFragment.kt
> +                    )
observe가 될때마다 매번 adapter를 초기화해주는거같아요!
observe에는 submitList만 들어가고 observe 바깥에 setAdapter부분이 들어가는게 좋아보입니다!

2023-10-12 11:37 UTC, kimmandoo commented on presentation/src/main/java/com/shypolarbear/presentation/ui/ranking/RankingFragment.kt
> +                    )
해당부분 로직 수정했습니다!

2023-10-12 11:38 UTC, jinukeu approved these changes
👍 굳입니다요!

2023-10-13 01:28 UTC, BEEEAM-J commented on presentation/src/main/java/com/shypolarbear/presentation/ui/ranking/RankingViewModel.kt
> +    private fun loadTotalRanking(lastCommentId: Int? = null): Job {
Job 객체를 반환하는 특별한 이유가 있을까요??
반환한 Job을 loadRankingData() 함수에서 사용하지 않는거 같아서 질문합니다!
반환 타입 명시 안하고 그냥 viewModelScope.launch 해도 잘 동작할 거 같은 생각이 들어용

2023-10-13 01:40 UTC, BEEEAM-J approved these changes
무한 스크롤 구현할 때 Job 반환해서 코루틴 제어하는 건 생각도 못했었는데 배워갑니다~~

2023-10-13 02:31 UTC, merged